BEGIN;

ALTER TABLE IF EXISTS contas ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lojas ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS insumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS insumo_embalagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contagem_itens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS vendas_periodo ENABLE ROW LEVEL SECURITY;

COMMIT;
